name: GitHub Pages deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: |
          set -e
          npm run build
          npm run export
          touch ./out/.nojekyll
          echo "bluelogic.cloud" > ./out/CNAME
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.2.3
        with:
          branch: gh-pages
          folder: out
